#!/bin/bash
## #PBS -q debug
#PBS -q usplanck
#PBS -A usplanck
#PBS -l nodes=1:ppn=4
#PBS -l pvmem=5GB
## #PBS -l walltime=00:30:00
#PBS -l walltime=12:00:00
#PBS -N mcmc_1115
#PBS -e mcmc_1115.err
#PBS -o mcmc_1115.out
#PBS -m bea

cd /global/scratch2/sd/dpietrob/DM-haze/
pwd

## ------ You need to load modules in the runtask.sh script

pbsdsh /global/scratch2/sd/dpietrob/DM-haze/runtask.sh

## python run_final_mcmc.py -m 1115 -s 1 -o test_mcmc_chain
## python run_final_mcmc.py -m 1115 -s 2 -o test_mcmc_chain
## python run_final_mcmc.py -m 1115 -s 3 -o test_mcmc_chain
## python run_final_mcmc.py -m 1115 -s 4 -o test_mcmc_chain
